services:
  postgres:
    image: postgres:17-alpine
    container_name: petrecadelivery-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - petrecadelivery-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: petrecadelivery-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgpass
    networks:
      - petrecadelivery-net
    depends_on:
      postgres:
        condition: service_healthy

  kafka-init:
    image: busybox
    container_name: petrecadelivery-kafka-init
    command: chown -R 1000:1000 /var/lib/kafka/data
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - petrecadelivery-net

  kafka:
    image: apache/kafka-native:latest
    container_name: petrecadelivery-kafka
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Fixado o bind de IPs (0.0.0.0) para garantir que escute todas as interfaces do container
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9094,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9094,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      # Configurações para single-node (desenvolvimento)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "ci2wmz4XQ3-kG1B9W9m2Zw"
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - petrecadelivery-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: petrecadelivery-kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
    ports:
      - 8090:8080
    networks:
      - petrecadelivery-net
    depends_on:
      kafka:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway" # Vital for Linux to bridge to the host machine
    networks:
      -  petrecadelivery-net

  grafana:
    image: grafana/grafana:latest
    container_name: petrecadelivery-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin} # The master password for Grafana
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
    networks:
      - petrecadelivery-net
    depends_on:
      - prometheus

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: petrecadelivery-keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloakdb
      - KC_DB_USERNAME=${POSTGRES_USER:-postgres}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - KC_HOSTNAME_STRICT=false
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8082:8080"
    networks:
      - petrecadelivery-net
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  kafka_data:
  pgadmin_data:
  postgres_data:
  prometheus_data:
networks:
  petrecadelivery-net:
    driver: bridge