global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'petrecadelivery-microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'delivery-tracking:8080'
        - 'courier-management:8081'
        - 'service-registry:8761'
        - 'gateway:9999'