server.port: 8081

spring:
  application:
    name: courier-management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/courierdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: courier-management
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: 'com.petreca.petrecadelivery.*'
        spring.json.type.mapping:
          delivery-placed-event:com.petreca.petrecadelivery.courier.management.infrastructure.event.DeliveryPlacedIntegrationEvent,
          delivery-picked-up-event:com.petreca.petrecadelivery.courier.management.infrastructure.event.DeliveryPickedUpIntegrationEvent,
          delivery-fulfilled-event:com.petreca.petrecadelivery.courier.management.infrastructure.event.DeliveryFulfilledIntegrationEvent
    template:
      observation-enabled: true
      listener:
        observation-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /api/v1/couriers/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://${JAEGER_HOST:localhost}:4318/v1/traces