server.port: 8761

spring:
  application.name: service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        # SECURITY FIRST: Only expose exactly what we need. Never use '*'.
        include: health,prometheus,info
  endpoint:
    health:
      # Allows us to see database and Kafka connection status, not just "UP"
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces