{
 "title": "Petreca War Room",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Business KPIs (The Vault)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deliveries Placed vs Fulfilled",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"delivery-tracking\"} |= \"DeliveryPlacedEvent\" [1h]))"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({app=\"delivery-tracking\"} |= \"DeliveryFulfilledEvent\" [1h]))"
    }
   ]
  },
  {
   "title": "Golden Signals (Technical Health)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Global HTTP Traffic (Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (application)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Error Rate (Live)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (app) (rate({level=\"ERROR\"} [5m]))"
    }
   ]
  },
  {
   "title": "System Latency (The Speed of Magic)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m])) / sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}