server.port: 9999

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/petreca-realm

  application.name: gateway
  cloud:
    gateway.server.webflux:
      httpclient:
        connect-timeout: 10 #ms
        response-timeout: 300ms
      routes:
        - id: delivery-tracking-route
          uri: lb://delivery-tracking
          predicates:
            - Path=/api/v1/deliveries/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY
                method: GET,PUT
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 30ms
                  factor: 2
                timeout: 400ms
            - name: CircuitBreaker
              args:
                name: delivery-tracking-route-circuit-breaker
                statusCodes:
                  - 500
                  - 502
                  - 504
        - id: courier-management-route
          uri: lb://courier-management
          predicates:
            - Path=/api/v1/couriers/**
        - id: courier-management-public
          uri: lb://courier-management
          predicates:
            - Path=/public/couriers
            - Method=GET
          filters:
            - RewritePath=/public/couriers, /api/v1/couriers
            - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveriesQuantity,phone,true
        - id: courier-management-public-detail
          uri: lb://courier-management
          predicates:
            - Path=/public/couriers/**
            - Method=GET
          filters:
            - RewritePath=/public/couriers/?(?<segment>.*), /api/v1/couriers/$\{segment}
            - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveriesQuantity,phone,true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persist-authorization: true
    urls:
      - name: Courier Management API
        url: /api/v1/couriers/v3/api-docs
      - name: Delivery Tracking API
        url: /api/v1/deliveries/v3/api-docs
    oauth:
      clientId: petreca-api-client


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED #TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      delivery-tracking-route-circuit-breaker:
        baseConfig: default
        waitDurationInOpenState: 5000

management:
  endpoints:
    web:
      exposure:
        # SECURITY FIRST: Only expose exactly what we need. Never use '*'.
        include: health,prometheus,info
  endpoint:
    health:
      # Allows us to see database and Kafka connection status, not just "UP"
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces