server.port: 9999

spring:
  application.name: gateway
  cloud:
    gateway.server.webflux:
      httpclient:
        connect-timeout: 10 #ms
        response-timeout: 300ms
      routes:
        - id: delivery-tracking-route
          uri: lb://delivery-tracking
          predicates:
            - Path=/api/v1/deliveries/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY
                method: GET,PUT
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 30ms
                  factor: 2
                timeout: 400ms
            - name: CircuitBreaker
              args:
                name: delivery-tracking-route-circuit-breaker
                statusCodes:
                  - 500
                  - 502
                  - 504
        - id: courier-management-route
          uri: lb://courier-management
          predicates:
            - Path=/api/v1/couriers/**
        - id: courier-management-public
          uri: lb://courier-management
          predicates:
            - Path=/public/couriers
            - Method=GET
          filters:
            - RewritePath=/public/couriers, /api/v1/couriers
            - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveriesQuantity,phone,true
        - id: courier-management-public
          uri: lb://courier-management
          predicates:
            - Path=/public/couriers/**
            - Method=GET
          filters:
            - RewritePath=/public/couriers/?(?<segment>.*), /api/v1/couriers/$\{segment}
            - RemoveJsonAttributesResponseBody=pendingDeliveries,pendingDeliveriesQuantity,phone,true


eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED #TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      delivery-tracking-route-circuit-breaker:
        baseConfig: default
        waitDurationInOpenState: 5000