spring:
  application:
    name: delivery-tracking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/deliverydb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          delivery-placed-event:com.petreca.petrecadelivery.delivery.tracking.domain.event.DeliveryPlacedEvent,
          delivery-picked-up-event:com.petreca.petrecadelivery.delivery.tracking.domain.event.DeliveryPickedUpEvent,
          delivery-fulfilled-event:com.petreca.petrecadelivery.delivery.tracking.domain.event.DeliveryFulfilledEvent
    template:
      observation-enabled: true
      listener:
        observation-enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8082/realms/delivery-realm}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8082/realms/delivery-realm/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 20ms
      instances:
        Retry_CourierAPIClient_payoutCalculation:
          baseConfig: default
          maxAttempts: 3
          retryExceptions:
            - org.springframework.web.client.ResourceAccessException
          ignoreExceptions:
            - org.springframework.web.client.HttpServerErrorException
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED #TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      CircuitBreaker_CourierAPIClient_payoutCalculation:
        baseConfig: default
        waitDurationInOpenState: 5000

springdoc:
  api-docs:
    path: /api/v1/deliveries/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://${JAEGER_HOST:localhost}:4318/v1/traces